# Generated by Django 5.2.17 on 2026-08-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=128)),
                ('package_name', models.CharField(max_length=128)),
                ('venue_location', models.CharField(max_length=255)),
                ('guest_count', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed & Reserved'), ('completed', 'Completed Event'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('estimated_amount', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wedding Date Booking',
                'verbose_name_plural': 'Wedding Date Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Direct Phone Call')], default='whatsapp', max_length=32)),
                ('replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Inquiry / Message',
                'verbose_name_plural': 'Client Inquiries / Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('couple', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=128)),
                ('cover_image', models.URLField(max_length=1000)),
                ('excerpt', models.TextField()),
                ('full_story', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of string highlights')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Sacred Story',
                'verbose_name_plural': 'Featured Sacred Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('all', 'All Ceremonies'), ('muhurtham', 'Sacred Muhurtham'), ('couples', 'Couples & Pre-Wedding'), ('rituals', 'Rituals & Traditions'), ('portraits', 'Portraits & Heirloom')], default='muhurtham', max_length=64)),
                ('category_label', models.CharField(max_length=128)),
                ('location', models.CharField(default='Madurai', max_length=128)),
                ('image_url', models.URLField(max_length=1000)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio Photo',
                'verbose_name_plural': 'Portfolio Photos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=64)),
                ('price_raw', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=128)),
                ('photographers', models.CharField(max_length=255)),
                ('inclusions', models.JSONField(default=list, help_text='List of string inclusions')),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Investment Package',
                'verbose_name_plural': 'Investment Packages',
                'ordering': ['order', 'price_raw'],
            },
        ),
        migrations.CreateModel(
            name='SignatureService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('deliverables', models.JSONField(default=list, help_text='List of deliverables')),
                ('starting_price', models.CharField(max_length=64)),
                ('price_raw', models.IntegerField(default=0)),
                ('cover_image', models.URLField(max_length=1000)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Signature Offering / Service',
                'verbose_name_plural': 'Signature Offerings / Services',
                'ordering': ['order', 'price_raw'],
            },
        ),
        migrations.CreateModel(
            name='StudioInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aaruthra Studio', max_length=255)),
                ('tagline', models.CharField(default='Sacred Tamil Wedding Photography & Heirloom Cinematography', max_length=255)),
                ('city', models.CharField(default='Madurai', max_length=128)),
                ('state', models.CharField(default='Tamil Nadu, India', max_length=128)),
                ('address', models.CharField(default='East Veli Street, Near Meenakshi Amman Temple, Madurai - 625001', max_length=255)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=32)),
                ('whatsapp_number', models.CharField(default='919876543210', max_length=32)),
                ('email', models.EmailField(default='namaste@aaruthrastudio.com', max_length=254)),
                ('founder_name', models.CharField(default='Aaruthra Selvan', max_length=128)),
                ('experience_years', models.CharField(default='12+', max_length=32)),
                ('weddings_photographed', models.CharField(default='450+', max_length=32)),
                ('heirloom_albums', models.CharField(default='380+', max_length=32)),
                ('client_rating', models.CharField(default='4.9/5', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Studio Profile & Contact Information',
                'verbose_name_plural': 'Studio Profile & Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('couple_names', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='Bride & Groom', max_length=128)),
                ('wedding_date_venue', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('quote', models.TextField()),
                ('avatar_url', models.URLField(max_length=1000)),
                ('verified', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['order', '-id'],
            },
        ),
    ]
