# Generated by Django 5.2.17 on 2026-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studioinfo",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Homepage hero banner background",
                null=True,
                upload_to="studio/",
            ),
        ),
        migrations.AddField(
            model_name="studioinfo",
            name="parallax_image",
            field=models.ImageField(
                blank=True,
                help_text="Full-bleed quote/parallax section background",
                null=True,
                upload_to="studio/",
            ),
        ),
        migrations.AddField(
            model_name="studioinfo",
            name="photographer_image",
            field=models.ImageField(
                blank=True,
                help_text="Founder/photographer portrait for the About section",
                null=True,
                upload_to="studio/",
            ),
        ),
        migrations.AlterField(
            model_name="featuredstory",
            name="cover_image",
            field=models.ImageField(upload_to="stories/"),
        ),
        migrations.AlterField(
            model_name="galleryphoto",
            name="image_url",
            field=models.ImageField(upload_to="gallery/"),
        ),
        migrations.AlterField(
            model_name="signatureservice",
            name="cover_image",
            field=models.ImageField(upload_to="services/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="avatar_url",
            field=models.ImageField(upload_to="testimonials/"),
        ),
    ]